### ISSUE TITLE
Weird searchColor Issue

### ISSUE THREAD

**Issue by dink** [phoboslab/picturelicious#1]
Very nice script -- thank you for sharing.

I'm having a issue when searching by color, where the DB queries are printed above the header, and no results are given except for 0x000000, which works as intended. I've imported about 150 test images in various colors to be sure, but no luck.

See here: http://i.imgur.com/lG5Qb.jpg

I'm testing it on local XAMPP, latest.

Any ideas what might be causing this?

EDIT: Nevermind, it works fine on a live server. I guess XAMPP has some issues.

**Comment by nanashiRei** [comment]
I'm having this issue on my live server and i tried everything i could to fix this, on my EasyPHP installation at home it works...

**Comment by phoboslab** [comment]
I believe this is an issue with certain MySQL versions. Probably some (strict) error/warning settings, but I'm not sure exactly. 

As a workaround, you could try to change the color values in the database to `signed SMALLINT` instead of `unsigned TINYINT`:

``` mysql
ALTER TABLE `pl_imagecolors`
CHANGE `r` `r` SMALLINT( 3 ) NOT NULL DEFAULT '0', 
CHANGE `g` `g` SMALLINT( 3 ) NOT NULL DEFAULT '0', 
CHANGE `b` `b` SMALLINT( 3 ) NOT NULL DEFAULT '0';
```

**Comment by nanashiRei** [comment]
This lovely little piece of SQL made me smile :+1: 

Here have some :love_letter: 

``` php
$gFindCl = new Google\People\FindAwesome();
$githubUser = $gFindCl->FromGithub()->byRepository('picturelicious')->getOriginalCreator();
$githubUser->giveLove(pow(2,32)); // Here is some love for you, thanks :P
```
