### ISSUE TITLE
Voting issue

### ISSUE THREAD

**Issue by Quasimodo** [phoboslab/picturelicious#2]
Hi,

first of all thank you for this fantastic share but i have a small problem with voting. 
Each time someone wants to vote the wheel just keeps spinning and spinning and it does not refresh. When you go to another pic and then come back the vote is there but i would prefer to have it the right way. Can you help with it pls?

Thank you :)

**Comment by phoboslab** [comment]
The PHP script that accepts the Ajax request for the vote probably returns an error, is in the wrong MIME type or has some additional content that prevents the response from being parsed as JavaScript - thus JavaScript assumes the vote never finishes.

Have a look at the debug console of your browser when you vote. You should see an error, or at least a response that's somehow garbled.

**Comment by Quasimodo** [comment]
Refused to set unsafe header "Content-length"
Refused to set unsafe header "Connection"
POST http://www.xxx.xx/json.php?rate 500 (Internal Server Error) picturelicious.js:323

This is what popped up... Can you help me with it?

**Comment by phoboslab** [comment]
I'm not sure what's going on. The [json.php](https://github.com/phoboslab/picturelicious/blob/master/picturelicious/json.php) never explicitly sets these headers, so this is probably an issue with PHP and/or your Webserver.

**Comment by Quasimodo** [comment]
I already contacted my hosting comp. but they said its something wrong with the script. Could it be something with php.ini file? Some permissions that i should enable? Or could you send me en example of the php.ini file that you use on demo picturelicious net/ ?

Thank you for any help.

**Comment by phoboslab** [comment]
Ah, just googled it. The "Refused to set unsafe..." message is a client side warning, not an error and not server side. So I assume there's still something else going on on the server. Post a link to your installation and I'll have a look.

**Comment by Quasimodo** [comment]
www.redheadsworld.com

thank you very much...

**Comment by phoboslab** [comment]
The server returns a 500 error but is suppressing error output. Check your webserver logs for the details.

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to completeyour request.
(...)
More information about this error may be availablein the server error log.
```

**Comment by Quasimodo** [comment]
[Thu Jan 17 00:05:03 2013] [error] [client **_.**_.**_.**_] File does not exist: /home/*****/public_html/redheadsworld.com/500.shtml, 

Error log showed this.

So i just created an empty 500.shtml file but it doesn't work :( At least there are no more errors on server...

**Comment by phoboslab** [comment]
The error 500.shtml is only needed when there is an error 500. We need to figure out _why_ there is an error 500 in the first place. 

If it's not in your logs, try turning error reporting on in your `php.ini`; google may help :)

**Comment by Quasimodo** [comment]
Error reporting turned on but no but no reports about any Error :(. What now?

**Comment by phoboslab** [comment]
http://stackoverflow.com/questions/845021/how-to-get-useful-error-messages-in-php

**Comment by Quasimodo** [comment]
![Untitled1](https://f.cloud.github.com/assets/3275275/81201/64108170-6302-11e2-9796-7adab436e18d.jpg)

all turned on but no error messages.

**Comment by phoboslab** [comment]
Did you restart the server? Are you sure you modified the right `php.ini`? Sometimes there are several php.ini files in different directories, but only one is loaded - consult `phpinfo();` for details.

You may also want to ask a general PHP forum for help. Getting PHP error information is not specific to this software.

**Comment by Quasimodo** [comment]
Had some help but still no luck :(

**Comment by Netrogen** [comment]
Hi Quasimodo, did you manage to find a fix in the end?  I was having the exact same problem, luckily my hosting providers solved it for me.  Let me know if you're still around and I'll post a solution...

**Comment by Quasimodo** [comment]
Hi Netrogen, please heeeelp, I'm still having the problem and cant find a way to fix it...

**Comment by Netrogen** [comment]
Hi, The first thing to try is comment out a line in json.php, its the header( 'Content-Type', 'text/plain' ); line, just put // in front of it. Won't hurt to clear cache of browsers before you test again.

Now when I did this I got timezone errors, so if this happens you need to modify your php.ini file - but we'll get to that as and when we need to.

Hope this helps, let me know how you get on...

**Comment by Quasimodo** [comment]
ITS FINALLY WOOOOORKING THANK YOU NETROGEN... :)))

**Comment by Netrogen** [comment]
You're very welcome.  It was the guys at TSOHost who fixed it for me, they deserve a mention.

**Comment by Quasimodo** [comment]
Pass them my thank you then ;)
