### ISSUE TITLE
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead

### ISSUE THREAD

**Issue by 4Ducky** [phoboslab/picturelicious#5]
Hey Buddy there are a new error with PHP 5.5

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /home/u955216812/public_html/lib/db.php on line 55

**Comment by phoboslab** [comment]
Replace Line 55 of lib/db.php with the following:

``` php
$q = preg_replace_callback(
    '/:(\d+)/',
    function($m) use ($params) { 
        return self::quote($params[$m[1] - 1], $m[2]);
    },
    $q
);
```

I'm wary to update, since this needs at least php5.3, while the current Picturelicious version runs on php4. For now, the deprecation message can also be safely ignored.

**Comment by 4Ducky** [comment]
Thank you buddy :+1:

**Comment by radog** [comment]
Thank you, work fine!
